### ISSUE TITLE
current status

### ISSUE THREAD

**Issue by slangens1** [TobiEiss/go-textfsm#1]
Hi,
I have a interest in helping out on this library, What is the current status?

**Comment by TobiEiss** [comment]
Hi,
oh yes! Great! I will use this weekend to continue.
I go through the textfsm-tutorial and implement the features step by step. Currently i'm here: https://github.com/google/textfsm/wiki/Code-Lab#parsing-tabular-data

Check out the tests to understand how it works.

**Comment by slangens1** [comment]
ah, I noticed some regular expressions do not parse properly, like "Value Whatever ([0-9]+)"

**Comment by TobiEiss** [comment]
feel free to implement missing stuff 😄
