### ISSUE TITLE
wrong recording

### ISSUE THREAD

**Issue by Ali-aqrabawi** [TobiEiss/go-textfsm#15]
`go-textfsm` is recording a `Columns` instead of `Raws`.

for example,
 template :

    Value IFACE (\S+)
    Value Required NAME (\S+)
    Value STATUS (down|up)
    Value ERROR (.*)

    Start
      ^Interface:\s+${IFACE}
      ^\s+name\s+"${NAME}"
      ^\s+status\s+${STATUS}
      ^\s+errors:\s+${ERROR} -> Record

input `file`:

    Interface: Gi0/1
        name "wan1"
        status up
        errors: output Queue errors
    Interface: Gi0/2
        name "wan2"
        status down
        errors: input Queue errors

in `go-textfsm` the records will be like :

    [Gi0/1 Gi0/2]
    [wan1 wan2 ]
    [up down]
    [output Queue errors input Queue errors]

while in `google/textfsm` it will be :

    ['Gi0/1', 'wan1', 'up', 'output Queue errors']
    ['Gi0/2', 'wan2', 'down', 'input Queue errors']

**Comment by Ali-aqrabawi** [comment]
@TobiEiss , please have a look at this, if you do agree on it, it would be better to fix it before continue working on the project,

**Comment by TobiEiss** [comment]
@Ali-aqrabawi your totally right. I'll fix this...

**Comment by TobiEiss** [comment]
I think i'm done 💪
@Ali-aqrabawi please checkout [this tests](https://github.com/TobiEiss/go-textfsm/blob/master/pkg/process/process_test.go)

**Comment by Ali-aqrabawi** [comment]
@TobiEiss you the man :+1:
