### ISSUE TITLE
end of line (i.e $$) and `?` support 

### ISSUE THREAD

**Issue by Ali-aqrabawi** [TobiEiss/go-textfsm#17]
end of line in `textFSM` should be optional and defined by user using `$$`,

1. `go-textfsm` append each `matchingLine` with `$` which making it not optional.
2. also it does not accept `$$` and raises `illegal token` if exist in template.
3. `go-textfsm` does not accept `?` char.

**Comment by TobiEiss** [comment]
Done by [this commit](https://github.com/TobiEiss/go-textfsm/commit/028f3a2f17b0e4e5f731534c8d621cdbad5f58cc)
Thank you @Ali-aqrabawi
