### ISSUE TITLE
an example would be helpful

### ISSUE THREAD

**Issue by Ali-aqrabawi** [TobiEiss/go-textfsm#2]
can we have an example of how to run it

**Comment by Geoffrey42** [comment]
+1 for a basic README. I am currently using textFSM python version and I would be glad to try this golang version for some cool projects.

**Comment by TobiEiss** [comment]
Yes, i will do this these days. Please stay tuned!

**Comment by manivannanpk** [comment]
Hi

What is the kind of license go-textfsm is distributed with?

Thanks,
Mani

**Comment by TobiEiss** [comment]
Hi,
I choosed MIT. Thank you!

**Comment by manivannanpk** [comment]
Thanks.

Another question - is there a way to get the headers along with the parsed rows? (i.e. list of headers as the first row)

**Comment by Ali-aqrabawi** [comment]
@manivannanpk you can get the headers and their respective index :

    for i,value := range abstractStatementT.Vals{
		fmt.Println(value.Variable) // this will print the "header" name
	}

**Comment by manivannanpk** [comment]
Thanks for the reply. I don't know that abstractStatementT is. I am using ast.Vals to retrieve the header list. I hope that is fine.

**Comment by Ali-aqrabawi** [comment]
example is added to `README.md` thanks @TobiEiss
