### ISSUE TITLE
Clearall record action support

### ISSUE THREAD

**Issue by Ali-aqrabawi** [TobiEiss/go-textfsm#25]
like [this](https://github.com/google/textfsm/wiki/TextFSM#record-actions)

**Comment by TobiEiss** [comment]
[Solved](https://github.com/TobiEiss/go-textfsm/pull/27)
Thank you @Ali-aqrabawi

**Comment by TobiEiss** [comment]
[Solved](https://github.com/TobiEiss/go-textfsm/pull/27)
Thank you @Ali-aqrabawi
