### ISSUE TITLE
"|" operator is an unknown token,

### ISSUE THREAD

**Issue by Ali-aqrabawi** [TobiEiss/go-textfsm#3]
in `textfsm` should accept `|` as a token for `or`, 
if my tamplate has `|` i get `illegal token`

**Comment by TobiEiss** [comment]
Fixed. Thank you @Ali-aqrabawi 

https://github.com/TobiEiss/go-textfsm/commit/446dbdf793b09a479d7bc49a903f5ea49cd86604
