### ISSUE TITLE
Fails to parse a simple input file

### ISSUE THREAD

**Issue by manivannanpk** [TobiEiss/go-textfsm#30]
Hi

Please try parsing the attached file source.txt with the template template.txt. go-textfsm does not output any record whereas the Python implementation of textfsm outputs [['100', '2']] which is the expected output.

[source.txt](https://github.com/TobiEiss/go-textfsm/files/3550784/source.txt)
[template.txt](https://github.com/TobiEiss/go-textfsm/files/3550785/template.txt)

**Comment by manivannanpk** [comment]
PFA the modified template.txt with the Record action at the end. Even with this, go-textfsm does not capture any text.
[template.txt](https://github.com/TobiEiss/go-textfsm/files/3550809/template.txt)

**Comment by Ali-aqrabawi** [comment]
by default google textfsm record the last match even if no record statment, but in `go-textfsm` a `record` is required.

to solve your issue just add `->Record`

    Value FirstValue (\d+)
    Value SecondValue (\d+)

    Start  
      ^${FirstValue}.*
      ^CPUs: ${SecondValue}.* -> Record

**Comment by TobiEiss** [comment]
Okay. I will fix this!

**Comment by TobiEiss** [comment]
Fixed with this [commit](https://github.com/TobiEiss/go-textfsm/commit/c0c22e815796e0b54a78dfae12cdb81dafd07fac)
