### ISSUE TITLE
Required Seems Not To Be Working The Same As In Python's TFM

### ISSUE THREAD

**Issue by metajar** [TobiEiss/go-textfsm#31]
I have started looking into this but it appears that the Required is not working as expected.

Test Config Source:
[testConfig.txt](https://github.com/TobiEiss/go-textfsm/files/3576276/testConfig.txt)

Test Template:
[lsp.txt](https://github.com/TobiEiss/go-textfsm/files/3576284/lsp.txt)

When running this in python's textfsm I receive what I expect:
```
[['5455', 'RTRA->RTRB->LAB', 'Loopback65', '8.8.8.8']]
```
But when running with go I get the following:
```
[   15.21.66.154]
[5455 RTRA->RTRB->LAB Loopback65 8.8.8.8]
```
I would assume that since it is required that it shouldn't add the first Row at all.

**Comment by Ali-aqrabawi** [comment]
thanks for submitting this issue, i'm looking into it,

**Comment by TobiEiss** [comment]
It is [fixed.](https://github.com/TobiEiss/go-textfsm/commit/9afa7e3861d4f869ca0a1930219d5bff1e483f62)
Thanks a lot @Ali-aqrabawi
