### ISSUE TITLE
Issue - Duplicate Rows Are Recorded - Python TextFSM Tests Proper

### ISSUE THREAD

**Issue by metajar** [TobiEiss/go-textfsm#33]
I am testing the following template and config. 

Template:
https://gist.github.com/metajar/9965f7ed135a24acd1fc455f88d319bc

Test Config:
https://gist.github.com/metajar/63362dd0273fa0388d784edd2c56e2ab

In python I receive:
```python
['192.168.74.22', '', 'INERNALCPE', 'INTERNAL:CPE:ROUTEREFLECTOR', '', '']
['192.168.74.23', '', 'INERNALCPE', 'INTERNAL:CPE:ROUTEREFLECTOR', '', '']
['192.168.74.24', '', 'INERNALCPE', 'INTERNAL:CPE:ROUTEREFLECTOR', '', '']
['192.168.74.25', '', 'INERNALCPE', 'INTERNAL:CPE:ROUTEREFLECTOR', '', '']
['172.31.255.11', '', 'EXTERNALBLUE', 'EXTERNAL:CPE:ROUTEREFLECTOR', 'reject', 'reject']
['1.1.1.1', '808', '808HAWAII', 'EXTERNAL:CUSTOMER:808', '', '']
['2.2.2.2', '', '1299TT', 'FULLROUTES:TT', '', 'TT']
['19.12.12.1', '', '19NG', 'INTERNAL:ROUTES:VPN', 'reject-some', 'reject-them']
['32.12.12.12', '9999', 'BLACKHOLE', 'EXTERNAL:SERVICEVPN:100', '', '']
['23.23.23.23', '9082', '23S-policy', 'EXTERNAL:SERVICEVPN:200', '', '']
```

But unfortunately with the Go-TextFSM I see the following:
```go
["192.168.74.23" "" "INERNALCPE" "INTERNAL:CPE:ROUTEREFLECTOR" "" ""]
["192.168.74.23" "" "INERNALCPE" "INTERNAL:CPE:ROUTEREFLECTOR" "" ""]
["192.168.74.24" "" "INERNALCPE" "INTERNAL:CPE:ROUTEREFLECTOR" "" ""]
["192.168.74.25" "" "INERNALCPE" "INTERNAL:CPE:ROUTEREFLECTOR" "" ""]
["172.31.255.11" "" "EXTERNALBLUE" "EXTERNAL:CPE:ROUTEREFLECTOR" "reject" "reject"]
["172.31.255.11" "" "EXTERNALBLUE" "EXTERNAL:CPE:ROUTEREFLECTOR" "reject" "reject"]
["2.2.2.2" "808" "808HAWAII" "EXTERNAL:CUSTOMER:808" "reject" "reject"]
["2.2.2.2" "808" "1299TT" "FULLROUTES:TT" "reject" "TT"]
["2.2.2.2" "808" "1299TT" "FULLROUTES:TT" "reject" "TT"]
["19.12.12.1" "808" "19NG" "INTERNAL:ROUTES:VPN" "reject-some" "reject-them"]
["19.12.12.1" "808" "19NG" "INTERNAL:ROUTES:VPN" "reject-some" "reject-them"]
["32.12.12.12" "9999" "BLACKHOLE" "EXTERNAL:SERVICEVPN:100" "reject-some" "reject-them"]
["23.23.23.23" "9082" "23S-policy" "EXTERNAL:SERVICEVPN:200" "reject-some" "reject-them"]
["23.23.23.23" "9082" "23S-policy" "EXTERNAL:SERVICEVPN:200" "reject-some" "reject-them"]
```

Is there something within the templating that I need to change to work with Go-TextFSM?

**Comment by TobiEiss** [comment]
No, the result of google's textfsm and go-textfsm should be the same.
I think i've found the problem. But i need some time to fix this. I will try to fix this today. Please stay tuned!

**Comment by metajar** [comment]
Awesome! Thank you.

**Comment by TobiEiss** [comment]
The fix in my mind was another one 😬.
But I found the issue: ` ^.*! -> Record BGP`
It is the "State" after `Record`. That isn't implemented right now. I found a lot of examples in the internet but i miss the point how it works 😞.

@metajar can you please explain what the state next to `Record` means? - Thank you!

**Comment by Ali-aqrabawi** [comment]
@TobiEiss this mean take a `record` and go to `BGP` state to parse next line,

**Comment by TobiEiss** [comment]
Ah okay. So ‘BGP‘ waits to continue..
Okay. I‘ve to fix the state machine.

**Comment by TobiEiss** [comment]
Thank you @Ali-aqrabawi for the [fix](https://github.com/TobiEiss/go-textfsm/commit/5cd3dd091b30e28139f9590c67fc3133ef5ed1b8)
