### ISSUE TITLE
Value with Record action is considered to be mandatory

### ISSUE THREAD

**Issue by manivannanpk** [TobiEiss/go-textfsm#40]
[test.txt](https://github.com/TobiEiss/go-textfsm/files/3955410/test.txt)
[template.txt](https://github.com/TobiEiss/go-textfsm/files/3955412/template.txt)

PFA the template and text files.

Expected output:
foo	bar	xyz
"100" "200" ""
(This is the output from Python TextFSM library.)

Actual output:
(Empty)

The value xyz is treated as mandatory probably because it appears along with the Record action in the template. 

Actually the Record action itself is not mandatory. This is another deviation from the original Python library.

**Comment by Ali-aqrabawi** [comment]
related to #30

**Comment by TobiEiss** [comment]
On my way to fix this.
I understand the problem. But i don't understand the logic behind that thing. If i say "last rule in 'Start-State' have not to match, but write to record".

What is for example with this template (TestCase 7):
```
       Destination        Gateway                      Dist/Metric Last Change
       -----------        -------                      ----------- -----------
  B EX 0.0.0.0/0          via 192.0.2.73                  20/100        4w0d
                          via 192.0.2.201
                          via 192.0.2.202
                          via 192.0.2.74
  B IN 192.0.2.76/30     via 203.0.113.183                200/100        4w2d
  B IN 192.0.2.204/30    via 203.0.113.183                200/100        4w2d
  B IN 192.0.2.80/30     via 203.0.113.183                200/100        4w2d
  B IN 192.0.2.208/30    via 203.0.113.183                200/100        4w2d
```
```
Value Protocol (\S)
Value Type (\S\S)
Value Prefix (\S+)
Value Gateway (\S+)
Value Distance (\d+)
Value Metric (\d+)
Value LastChange (\S+)

Start
  ^.*----- -> Routes

Routes
  ^  ${Protocol} ${Type} ${Prefix}\s+via ${Gateway}\s+${Distance}/${Metric}\s+${LastChange} -> Record
```
In this case it would write in every mismatch a line to record. Or is there anything i don't understand?

**Comment by Ali-aqrabawi** [comment]
@TobiEiss  the case in this issue is different than the example you brought, 
if a line is not a match it will be ignored, so TestCase7 is correct,

the case in this issue is that if you have this text:
    
    name FastEthernet0
    ip 10.10.10.1

and the template:

    Value Name (\S+)
    Value Address (\S+)
    Value Status

    Start
         ^name ${Name}
         ^Address ${Address}
         ^Status ${Status} -> Record

in this case `Status` is not in the text file, but the result will be `[FastEthernet0 10.10.10.1]`
because what is left in the buffer will be added as record at `EOF`.

if the text was:

    name FastEthernet0
    ip 10.10.10.1
    name FastEthernet2
    ip 20.20.20.1

the result will be  `[FastEthernet2 20.20.20.1]` becasue these are the data collected when reaching `EOF`.

i hope that explain it.
