### ISSUE TITLE
Required Value Option supprt

### ISSUE THREAD

**Issue by Ali-aqrabawi** [TobiEiss/go-textfsm#6]
add support for `Required` option,
related to #5

**Comment by Ali-aqrabawi** [comment]
i will work on this.

**Comment by TobiEiss** [comment]
Done by [this](https://github.com/TobiEiss/go-textfsm/pull/16)
Thank you @Ali-aqrabawi <3

**Comment by TobiEiss** [comment]
Done by [this](https://github.com/TobiEiss/go-textfsm/pull/16)
Thank you @Ali-aqrabawi <3
