### ISSUE TITLE
List Value Option support

### ISSUE THREAD

**Issue by Ali-aqrabawi** [TobiEiss/go-textfsm#7]
add support for `List` value option.
related to this [this](https://github.com/TobiEiss/go-textfsm/issues/5)

**Comment by Ali-aqrabawi** [comment]
i'm working on this.

**Comment by TobiEiss** [comment]
@Ali-aqrabawi checkout the #8. If applicable implement `List` similar to `Filldown`.

**Comment by Ali-aqrabawi** [comment]
will do
