### ISSUE TITLE
Filldown Value Option support

### ISSUE THREAD

**Issue by Ali-aqrabawi** [TobiEiss/go-textfsm#8]
add support for `Filldown` value option
related to [this](https://github.com/TobiEiss/go-textfsm/issues/5)

**Comment by TobiEiss** [comment]
I add the support for `Filldown` currently

**Comment by TobiEiss** [comment]
Done by this [commit](https://github.com/TobiEiss/go-textfsm/commit/412cc2135170c4605317861ca9a3527e6e199ff6l)
